<a href="https://colab.research.google.com/github/rhindupriya/Machine-Learning/blob/main/1_days_R_Hindu_192210151_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression
X = np.array([
    [4, 64, 4000],
    [6, 128, 4500],
    [8, 128, 5000],
    [12, 256, 6000],
    [3, 32, 3500]
])
y = np.array([15, 20, 25, 35, 10])

model = LinearRegression()
model.fit(X, y)

new_mobile = np.array([[8, 256, 5000]])

price = model.predict(new_mobile)

print("Predicted Mobile Price:", price)

Predicted Mobile Price: [25.]


In [2]:
import numpy as np
from sklearn.tree import DecisionTreeRegressor
X = np.array([[1],[2],[3],[4],[5],[6]])
y = np.array([200,220,250,300,320,350])

model = DecisionTreeRegressor()
model.fit(X,y)

future_month = np.array([[7]])

prediction = model.predict(future_month)

print("Predicted Future Sales:", prediction)

Predicted Future Sales: [350.]


2 Day

In [3]:
import numpy as np
from sklearn.linear_model import LinearRegression
X = np.array([[1000],[1500],[2000],[2500],[3000]])
y = np.array([200000,300000,400000,500000,600000])

model = LinearRegression()
model.fit(X,y)

size = np.array([[2200]])

price = model.predict(size)

print("Predicted House Price:", price)

Predicted House Price: [440000.]


In [4]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

data = load_iris()
X = data.data
y = data.target

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3)

models = {
    "Logistic Regression": LogisticRegression(),
    "KNN": KNeighborsClassifier(),
    "Decision Tree": DecisionTreeClassifier()
}

for name,model in models.items():
    model.fit(X_train,y_train)
    pred = model.predict(X_test)
    acc = accuracy_score(y_test,pred)
    print(name,"Accuracy:",acc)

Logistic Regression Accuracy: 0.9555555555555556
KNN Accuracy: 0.9777777777777777
Decision Tree Accuracy: 0.9555555555555556


3rd Day

In [5]:
from sklearn.naive_bayes import GaussianNB
import numpy as np
X = np.array([
    [30000,650],
    [40000,700],
    [50000,720],
    [20000,600],
    [35000,680]
])
y = np.array([0,1,1,0,1])

model = GaussianNB()
model.fit(X,y)

new_customer = np.array([[42000,710]])

result = model.predict(new_customer)

print("Loan Approval Prediction:", result)

Loan Approval Prediction: [1]


In [6]:
import numpy as np

data = np.arange(20)

np.random.shuffle(data)

train = data[:15]
test = data[15:]

print("Training Data:",train)
print("Testing Data:",test)

Training Data: [16 17  0  6 19  4 12  7 13  1 11 15  5  9  3]
Testing Data: [10 18  8  2 14]


4th Day


In [7]:
import numpy as np

data = np.array([45,60,72,88,55,91,67,49])
filtered = data[data > 60]

print("Filtered Data:", filtered)

print("Mean:", np.mean(filtered))
print("Median:", np.median(filtered))
print("Standard Deviation:", np.std(filtered))

Filtered Data: [72 88 91 67]
Mean: 79.5
Median: 80.0
Standard Deviation: 10.21028892833107


In [8]:
import numpy as np
sales = np.array([
    [200, 150, 300],
    [220, 180, 320],
    [250, 200, 350],
    [270, 210, 370]
])

print("Sales Data:\n", sales)
total_sales = np.sum(sales, axis=0)
average_sales = np.mean(sales, axis=0)

print("Total Sales:", total_sales)
print("Average Sales:", average_sales)
results = np.vstack((total_sales, average_sales))
np.savetxt("sales_summary.csv", results, delimiter=",", fmt="%.2f")

print("Results exported to sales_summary.csv")

Sales Data:
 [[200 150 300]
 [220 180 320]
 [250 200 350]
 [270 210 370]]
Total Sales: [ 940  740 1340]
Average Sales: [235. 185. 335.]
Results exported to sales_summary.csv


5th Day

In [9]:
import numpy as np

data = np.array([
['Sunny','Warm','Normal','Strong','Warm','Same','Yes'],
['Sunny','Warm','High','Strong','Warm','Same','Yes'],
['Rainy','Cold','High','Strong','Warm','Change','No'],
['Sunny','Warm','High','Strong','Cool','Change','Yes']
])

X = data[:,:-1]
y = data[:,-1]

hypothesis = ['0'] * len(X[0])

for i in range(len(X)):

    if y[i] == "Yes":
        for j in range(len(hypothesis)):

            if hypothesis[j] == '0':
                hypothesis[j] = X[i][j]

            elif hypothesis[j] != X[i][j]:
                hypothesis[j] = '?'

print("Most Specific Hypothesis:")
print(hypothesis)

Most Specific Hypothesis:
[np.str_('Sunny'), np.str_('Warm'), '?', np.str_('Strong'), '?', '?']


In [10]:
import pandas as pd

data = pd.DataFrame({
'Sky':['Sunny','Sunny','Rainy','Sunny'],
'Temp':['Warm','Warm','Cold','Warm'],
'Humidity':['Normal','High','High','High'],
'Wind':['Strong','Strong','Strong','Strong'],
'Water':['Warm','Warm','Warm','Cool'],
'Forecast':['Same','Same','Change','Change'],
'EnjoySport':['Yes','Yes','No','Yes']
})

X = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

S = ['0'] * len(X[0])
G = ['?'] * len(X[0])

for i in range(len(X)):

    if y[i] == 'Yes':
        for j in range(len(S)):
            if S[j] == '0':
                S[j] = X[i][j]
            elif S[j] != X[i][j]:
                S[j] = '?'

    elif y[i] == 'No':
        for j in range(len(S)):
            if S[j] != X[i][j]:
                G[j] = S[j]
            else:
                G[j] = '?'

print("Specific Hypothesis S:", S)
print("General Hypothesis G:", G)

Specific Hypothesis S: ['Sunny', 'Warm', '?', 'Strong', '?', '?']
General Hypothesis G: ['Sunny', 'Warm', '?', '?', '?', 'Same']


In [11]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder

data = pd.DataFrame({
'Outlook':['Sunny','Sunny','Overcast','Rain','Rain','Rain','Overcast','Sunny'],
'Temperature':['Hot','Hot','Hot','Mild','Cool','Cool','Mild','Cool'],
'Humidity':['High','High','High','High','Normal','Normal','Normal','High'],
'Wind':['Weak','Strong','Weak','Weak','Weak','Strong','Strong','Weak'],
'PlayTennis':['No','No','Yes','Yes','Yes','No','Yes','No']
})

le = LabelEncoder()

for column in data.columns:
    data[column] = le.fit_transform(data[column])

X = data.iloc[:,:-1]
y = data.iloc[:,-1]

model = DecisionTreeClassifier(criterion="entropy")
model.fit(X,y)

sample = [[2,1,1,0]]

prediction = model.predict(sample)

print("Prediction for new sample:", prediction)

Prediction for new sample: [0]


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
