<a href="https://colab.research.google.com/github/rhindupriya/Machine-Learning/blob/main/1_days_R_Hindu_192210151_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sklearn.linear_model import LinearRegression
X = np.array([
    [4, 64, 4000],
    [6, 128, 4500],
    [8, 128, 5000],
    [12, 256, 6000],
    [3, 32, 3500]
])
y = np.array([15, 20, 25, 35, 10])

model = LinearRegression()
model.fit(X, y)

new_mobile = np.array([[8, 256, 5000]])

price = model.predict(new_mobile)

print("Predicted Mobile Price:", price)

Predicted Mobile Price: [25.]


In [ ]:
import numpy as np
from sklearn.tree import DecisionTreeRegressor
X = np.array([[1],[2],[3],[4],[5],[6]])
y = np.array([200,220,250,300,320,350])

model = DecisionTreeRegressor()
model.fit(X,y)

future_month = np.array([[7]])

prediction = model.predict(future_month)

print("Predicted Future Sales:", prediction)

Predicted Future Sales: [350.]


2 Day

In [ ]:
import numpy as np
from sklearn.linear_model import LinearRegression
X = np.array([[1000],[1500],[2000],[2500],[3000]])
y = np.array([200000,300000,400000,500000,600000])

model = LinearRegression()
model.fit(X,y)

size = np.array([[2200]])

price = model.predict(size)

print("Predicted House Price:", price)

Predicted House Price: [440000.]


In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

data = load_iris()
X = data.data
y = data.target

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3)

models = {
    "Logistic Regression": LogisticRegression(),
    "KNN": KNeighborsClassifier(),
    "Decision Tree": DecisionTreeClassifier()
}

for name,model in models.items():
    model.fit(X_train,y_train)
    pred = model.predict(X_test)
    acc = accuracy_score(y_test,pred)
    print(name,"Accuracy:",acc)

Logistic Regression Accuracy: 0.9555555555555556
KNN Accuracy: 0.9777777777777777
Decision Tree Accuracy: 0.9555555555555556


3rd Day

In [ ]:
from sklearn.naive_bayes import GaussianNB
import numpy as np
X = np.array([
    [30000,650],
    [40000,700],
    [50000,720],
    [20000,600],
    [35000,680]
])
y = np.array([0,1,1,0,1])

model = GaussianNB()
model.fit(X,y)

new_customer = np.array([[42000,710]])

result = model.predict(new_customer)

print("Loan Approval Prediction:", result)

Loan Approval Prediction: [1]


In [ ]:
import numpy as np

data = np.arange(20)

np.random.shuffle(data)

train = data[:15]
test = data[15:]

print("Training Data:",train)
print("Testing Data:",test)

Training Data: [16 17  0  6 19  4 12  7 13  1 11 15  5  9  3]
Testing Data: [10 18  8  2 14]


4th Day


In [ ]:
import numpy as np

data = np.array([45,60,72,88,55,91,67,49])
filtered = data[data > 60]

print("Filtered Data:", filtered)

print("Mean:", np.mean(filtered))
print("Median:", np.median(filtered))
print("Standard Deviation:", np.std(filtered))

Filtered Data: [72 88 91 67]
Mean: 79.5
Median: 80.0
Standard Deviation: 10.21028892833107


In [ ]:
import numpy as np
sales = np.array([
    [200, 150, 300],
    [220, 180, 320],
    [250, 200, 350],
    [270, 210, 370]
])

print("Sales Data:\n", sales)
total_sales = np.sum(sales, axis=0)
average_sales = np.mean(sales, axis=0)

print("Total Sales:", total_sales)
print("Average Sales:", average_sales)
results = np.vstack((total_sales, average_sales))
np.savetxt("sales_summary.csv", results, delimiter=",", fmt="%.2f")

print("Results exported to sales_summary.csv")

Sales Data:
 [[200 150 300]
 [220 180 320]
 [250 200 350]
 [270 210 370]]
Total Sales: [ 940  740 1340]
Average Sales: [235. 185. 335.]
Results exported to sales_summary.csv


5th Day

In [ ]:
import numpy as np

data = np.array([
['Sunny','Warm','Normal','Strong','Warm','Same','Yes'],
['Sunny','Warm','High','Strong','Warm','Same','Yes'],
['Rainy','Cold','High','Strong','Warm','Change','No'],
['Sunny','Warm','High','Strong','Cool','Change','Yes']
])

X = data[:,:-1]
y = data[:,-1]

hypothesis = ['0'] * len(X[0])

for i in range(len(X)):

    if y[i] == "Yes":
        for j in range(len(hypothesis)):

            if hypothesis[j] == '0':
                hypothesis[j] = X[i][j]

            elif hypothesis[j] != X[i][j]:
                hypothesis[j] = '?'

print("Most Specific Hypothesis:")
print(hypothesis)

Most Specific Hypothesis:
[np.str_('Sunny'), np.str_('Warm'), '?', np.str_('Strong'), '?', '?']


In [ ]:
import pandas as pd

data = pd.DataFrame({
'Sky':['Sunny','Sunny','Rainy','Sunny'],
'Temp':['Warm','Warm','Cold','Warm'],
'Humidity':['Normal','High','High','High'],
'Wind':['Strong','Strong','Strong','Strong'],
'Water':['Warm','Warm','Warm','Cool'],
'Forecast':['Same','Same','Change','Change'],
'EnjoySport':['Yes','Yes','No','Yes']
})

X = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

S = ['0'] * len(X[0])
G = ['?'] * len(X[0])

for i in range(len(X)):

    if y[i] == 'Yes':
        for j in range(len(S)):
            if S[j] == '0':
                S[j] = X[i][j]
            elif S[j] != X[i][j]:
                S[j] = '?'

    elif y[i] == 'No':
        for j in range(len(S)):
            if S[j] != X[i][j]:
                G[j] = S[j]
            else:
                G[j] = '?'

print("Specific Hypothesis S:", S)
print("General Hypothesis G:", G)

Specific Hypothesis S: ['Sunny', 'Warm', '?', 'Strong', '?', '?']
General Hypothesis G: ['Sunny', 'Warm', '?', '?', '?', 'Same']


In [ ]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder

data = pd.DataFrame({
'Outlook':['Sunny','Sunny','Overcast','Rain','Rain','Rain','Overcast','Sunny'],
'Temperature':['Hot','Hot','Hot','Mild','Cool','Cool','Mild','Cool'],
'Humidity':['High','High','High','High','Normal','Normal','Normal','High'],
'Wind':['Weak','Strong','Weak','Weak','Weak','Strong','Strong','Weak'],
'PlayTennis':['No','No','Yes','Yes','Yes','No','Yes','No']
})

le = LabelEncoder()

for column in data.columns:
    data[column] = le.fit_transform(data[column])

X = data.iloc[:,:-1]
y = data.iloc[:,-1]

model = DecisionTreeClassifier(criterion="entropy")
model.fit(X,y)

sample = [[2,1,1,0]]

prediction = model.predict(sample)

print("Prediction for new sample:", prediction)

Prediction for new sample: [0]


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


6th day

In [ ]:
import pandas as pd
import numpy as np
from math import log2

# Sample dataset
data = {
    'Outlook': ['Sunny', 'Sunny', 'Overcast', 'Rain', 'Rain', 'Rain', 'Overcast', 'Sunny'],
    'Temperature': ['Hot', 'Hot', 'Hot', 'Mild', 'Cool', 'Cool', 'Mild', 'Hot'],
    'Humidity': ['High', 'High', 'High', 'High', 'Normal', 'Normal', 'Normal', 'High'],
    'Wind': ['Weak', 'Strong', 'Weak', 'Weak', 'Weak', 'Strong', 'Strong', 'Weak'],
    'Play': ['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No']
}

df = pd.DataFrame(data)

# Entropy calculation
def entropy(target):
    values, counts = np.unique(target, return_counts=True)
    entropy = sum([-counts[i]/sum(counts) * log2(counts[i]/sum(counts))
                   for i in range(len(values))])
    return entropy

# Information Gain
def information_gain(df, attribute, target):
    total_entropy = entropy(df[target])
    values, counts = np.unique(df[attribute], return_counts=True)

    weighted_entropy = sum([
        counts[i]/sum(counts) *
        entropy(df[df[attribute] == values[i]][target])
        for i in range(len(values))
    ])

    return total_entropy - weighted_entropy

# Heuristic Search for Best Split
def best_attribute(df, target):
    attributes = df.columns.drop(target)
    gains = {}

    for attr in attributes:
        gains[attr] = information_gain(df, attr, target)

    best = max(gains, key=gains.get)
    return best, gains

best_attr, gain_values = best_attribute(df, 'Play')

print("Information Gain for each attribute:")
for k, v in gain_values.items():
    print(k, ":", round(v, 4))

print("\nBest attribute for splitting:", best_attr)

Information Gain for each attribute:
Outlook : 0.6556
Temperature : 0.3444
Humidity : 0.0488
Wind : 0.0488

Best attribute for splitting: Outlook


7th day

In [5]:
import pandas as pd
import numpy as np
from math import log2

# Play Tennis dataset
data = {
    'Outlook': ['Sunny','Sunny','Overcast','Rain','Rain','Rain','Overcast','Sunny','Sunny','Rain','Sunny','Overcast','Overcast','Rain'],
    'Temperature': ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild'],
    'Humidity': ['High','High','High','High','Normal','Normal','Normal','High','Normal','Normal','Normal','High','Normal','High'],
    'Wind': ['Weak','Strong','Weak','Weak','Weak','Strong','Strong','Weak','Weak','Weak','Strong','Strong','Weak','Strong'],
    'PlayTennis': ['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']
}

df = pd.DataFrame(data)

# Function to calculate entropy
def entropy(target):
    values, counts = np.unique(target, return_counts=True)
    ent = 0
    for i in range(len(values)):
        p = counts[i] / sum(counts)
        ent -= p * log2(p)
    return ent

# Function to calculate information gain
def information_gain(data, attribute, target="PlayTennis"):
    total_entropy = entropy(data[target])
    values, counts = np.unique(data[attribute], return_counts=True)

    weighted_entropy = 0
    for i in range(len(values)):
        subset = data[data[attribute] == values[i]]
        weighted_entropy += (counts[i]/np.sum(counts)) * entropy(subset[target])

    return total_entropy - weighted_entropy

# ID3 algorithm
def id3(data, originaldata, features, target="PlayTennis", parent_node_class=None):

    if len(np.unique(data[target])) <= 1:
        return np.unique(data[target])[0]

    elif len(data) == 0:
        return np.unique(originaldata[target])[np.argmax(np.unique(originaldata[target], return_counts=True)[1])]

    elif len(features) == 0:
        return parent_node_class

    else:
        parent_node_class = np.unique(data[target])[np.argmax(np.unique(data[target], return_counts=True)[1])]

        gains = [information_gain(data, feature, target) for feature in features]
        best_feature_index = np.argmax(gains)
        best_feature = features[best_feature_index]

        tree = {best_feature:{}}

        features = [i for i in features if i != best_feature]

        for value in np.unique(data[best_feature]):
            subset = data[data[best_feature] == value]
            subtree = id3(subset, data, features, target, parent_node_class)
            tree[best_feature][value] = subtree

        return tree

# Build tree
features = df.columns[:-1]
tree = id3(df, df, features)

print("Decision Tree:")
print(tree)


# Function to classify new sample
def classify(sample, tree):
    for attribute in tree.keys():
        value = sample[attribute]
        subtree = tree[attribute][value]

        if isinstance(subtree, dict):
            return classify(sample, subtree)
        else:
            return subtree


# New sample
sample = {
    'Outlook': 'Sunny',
    'Temperature': 'Cool',
    'Humidity': 'High',
    'Wind': 'Strong'
}

prediction = classify(sample, tree)

print("\nNew Sample:", sample)
print("Prediction:", prediction)

Decision Tree:
{'Outlook': {'Overcast': 'Yes', 'Rain': {'Wind': {'Strong': 'No', 'Weak': 'Yes'}}, 'Sunny': {'Humidity': {'High': 'No', 'Normal': 'Yes'}}}}

New Sample: {'Outlook': 'Sunny', 'Temperature': 'Cool', 'Humidity': 'High', 'Wind': 'Strong'}
Prediction: No


In [6]:
import pandas as pd
import numpy as np
from math import log2

# dataset
data = {
    'Outlook':['Sunny','Sunny','Overcast','Rain','Rain','Rain'],
    'Temperature':['Hot','Hot','Hot','Mild','Cool','Cool'],
    'Humidity':['High','High','High','High','Normal','Normal'],
    'Wind':['Weak','Strong','Weak','Weak','Weak','Strong'],
    'Play':['No','No','Yes','Yes','Yes','No']
}

df = pd.DataFrame(data)

# entropy calculation
def entropy(target):
    values, counts = np.unique(target, return_counts=True)
    ent = 0
    for i in range(len(values)):
        p = counts[i]/sum(counts)
        ent -= p * log2(p)
    return ent


# heuristic search using information gain
def information_gain(data, attribute, target='Play'):

    total_entropy = entropy(data[target])

    values, counts = np.unique(data[attribute], return_counts=True)

    weighted_entropy = 0
    for i in range(len(values)):
        subset = data[data[attribute] == values[i]]
        weighted_entropy += (counts[i]/sum(counts)) * entropy(subset[target])

    gain = total_entropy - weighted_entropy
    return gain


# find best split attribute
def best_split(data):
    attributes = data.columns[:-1]
    gains = {}

    for attr in attributes:
        gains[attr] = information_gain(data, attr)

    best_attr = max(gains, key=gains.get)
    return best_attr, gains


best_attribute, gain_values = best_split(df)

print("Information Gain for each attribute:")
for attr in gain_values:
    print(attr, ":", gain_values[attr])

print("\nBest attribute to split (heuristic result):", best_attribute)

Information Gain for each attribute:
Outlook : 0.5408520829727552
Temperature : 0.20751874963942196
Humidity : 0.0
Wind : 0.4591479170272448

Best attribute to split (heuristic result): Outlook


8th day

In [7]:
import numpy as np
from sklearn import datasets
import matplotlib.pyplot as plt

# Load iris dataset
iris = datasets.load_iris()

# Use only two features for visualization
X = iris.data[:, :2]

# Binary classification: Setosa vs Not Setosa
y = (iris.target == 0).astype(int)

# Perceptron parameters
learning_rate = 0.01
epochs = 1000

# Initialize weights and bias
weights = np.zeros(X.shape[1])
bias = 0

# Perceptron training
for _ in range(epochs):
    for i in range(len(X)):
        linear_output = np.dot(X[i], weights) + bias
        prediction = 1 if linear_output >= 0 else 0

        update = learning_rate * (y[i] - prediction)
        weights += update * X[i]
        bias += update

print("Final Weights:", weights)
print("Bias:", bias)

# Prediction function
def predict(X):
    linear_output = np.dot(X, weights) + bias
    return np.where(linear_output >= 0, 1, 0)

# Test prediction
sample = X[10]
print("Sample features:", sample)
print("Predicted class:", predict(sample))

Final Weights: [-0.795  1.012]
Bias: 1.2500000000000009
Sample features: [5.4 3.7]
Predicted class: 1


In [8]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

# Load dataset
iris = load_iris()
X = iris.data
y = iris.target

# Convert output to one-hot encoding
y_encoded = np.eye(3)[y]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded, test_size=0.2, random_state=42
)

# Feature scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Network structure
input_size = 4
hidden_size = 6
output_size = 3

# Initialize weights
np.random.seed(0)
W1 = np.random.randn(input_size, hidden_size)
W2 = np.random.randn(hidden_size, output_size)

# Activation function
def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
    return x*(1-x)

# Training
learning_rate = 0.01
epochs = 5000

for epoch in range(epochs):

    # Forward propagation
    hidden_layer = sigmoid(np.dot(X_train, W1))
    output_layer = sigmoid(np.dot(hidden_layer, W2))

    # Error
    error = y_train - output_layer

    # Backpropagation
    d_output = error * sigmoid_derivative(output_layer)
    d_hidden = d_output.dot(W2.T) * sigmoid_derivative(hidden_layer)

    # Update weights
    W2 += hidden_layer.T.dot(d_output) * learning_rate
    W1 += X_train.T.dot(d_hidden) * learning_rate

# Testing
hidden_test = sigmoid(np.dot(X_test, W1))
output_test = sigmoid(np.dot(hidden_test, W2))

predictions = np.argmax(output_test, axis=1)
actual = np.argmax(y_test, axis=1)

accuracy = accuracy_score(actual, predictions)

print("Model Accuracy:", accuracy)

Model Accuracy: 1.0
